language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install pylint pep8
before_script:
  - mv CONFIG_SAMPLE.py CONFIG.py
script:
  - pep8 --max-line-length=120 python_template *.py
  - pylint python_template
  - ./python_template --help
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - peter@pakos.uk
